### PR TITLE
Upgrading to Rails 5

### PR DESCRIPTION
**Pull request by escowles**
* Also updating to ActiveFedora 11.1 and ActiveTriples 0.11

### CODE REVIEW

**Comment by escowles** [comment]
Now the tests pass, but both the jQuery uploader and the Browse Everything uploader have serious issues in the browser.  The jQuery uploader works, but fails to display the status of uploading items.  The Browse Everything uploader is completely broken.  No errors are logged in the Rails log or in the Javascript console in Chrome.

**Comment by escowles** [comment]
I think the problem is that none of the ES6 is working, but I can't figure out why.  None of the relevant sprocket/babel gems have changed versions.  I downgraded browse_everything back to the same version in master, and still it doesn't work.

I was able to get it working with vanilla javascript (see https://github.com/pulibrary/plum/commit/785e86b9cc84c91a531482a6061de5ac2b4ba34a), so I'm pretty sure it's something with the ES6 and not the HTML, controller, etc.

**Comment by tpendragon** [comment]
@escowles The problem was the `document.ready` in Blacklight wasn't working, so all of our `Blacklight.onLoad` code wasn't running. I'm not sure why that was the case, but a snippet in `application.js` fixes it.

**Comment by jpstroop** [comment]
:tada:

**Pull request merged**
