### PR TITLE
Hide label/legend in search bar.

### LINKED ISSUE #423: Hide "Search Plum: A Repository"

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #423

### CODE REVIEW

**Comment by escowles** [comment]
Would it be better to override the view than just hide the text with CSS?

**Comment by jpstroop** [comment]
I was wondering the same thing but forgot to comment last night.

**Comment by axamei** [comment]
Screen readers use the label element to describe the related input field so we want to keep that markup. And, setting the label to `display:none;` hides it from the screen reader. 

What we want to do is visually hide it, while making it readable by screen readers. See:  https://github.com/pulibrary/pul_assets/blob/6bb97a16ba5c03d1291c567a151a9e08b8a5d0c1/app/assets/stylesheets/utils/_mixins.scss#L25-L31

**Comment by tpendragon** [comment]
@axamei That seems right. It had that class and didn't seem to work. I'll take a closer look, thanks for the comment!

**Comment by tpendragon** [comment]
@axamei @jpstroop @escowles Updated.

**Pull request merged**
