### PR TITLE
Refactor manifest builder

### PR DESCRIPTION
**Pull request by tpendragon**
This bases the manifest builder on a series of "sub-builders", which actually mutate the manifest it eventually generates. It accepts extra builders through the services parameter, and could be refactored later to accept something like a BuilderFinder, if we find it useful. The common API of Builder#apply(manifest) should lower the churn on this file by a fair bit.

### CODE REVIEW

**Comment by tpendragon** [comment]
There's a commit in here to fix manifests for structure too, which we should get in before tomorrow's demo.

**Comment by jpstroop** [comment]
Cool 😎, nice and tidy. Remind me to _never_ show you the code that generates manifests for LAE

**Comment by jpstroop** [comment]
Sounds like you want to keep those commits separate?

**Comment by tpendragon** [comment]
> Sounds like you want to keep those commits separate?

Yup

**Pull request merged**
