### PR TITLE
Allow ImageWorks to pull metadata from bibdata

### LINKED ISSUE #1004: Scanned maps import from bibdata
- [ ] Modify bibdata to return bounding box
- [ ] Update New Image Work for to import from Voyager. (Like scanned resource)
- [x] Log MARC records that have missing or malformed 034 fields.

### PR DESCRIPTION
**Pull request by eliotjordan**
Allows ImageWorks to pull metadata from in from bibdata and to display image derivatives with the Universal Viewer. Closes #1004

### CODE REVIEW

**Comment by escowles** [comment]
This is probably going to conflict with https://github.com/pulibrary/plum/pull/1063

**Comment by eliotjordan** [comment]
Looks like it will conflict.

**Comment by eliotjordan** [comment]
I'll reconfigure after #1063 is merged.

**Comment by eliotjordan** [comment]
Rebased and updated with changes from 1063.

**Pull request merged**
