### PR TITLE
Excluding /spec from Coveralls, using vanilla SimpleCov locally

### PR DESCRIPTION
**Pull request by escowles**
Any opinions on running coverage locally @tpendragon @jpstroop?

### CODE REVIEW

**Comment by tpendragon** [comment]
Shouldn't we be using SimpleCov.start 'rails'?

**Comment by jpstroop** [comment]
@tpendragon ?

**Comment by jpstroop** [comment]
@tpendragon, Oops, your comment showed up after refreshing. I don't have an opinion. [SimpleCov.start 'rails'](https://github.com/colszowka/simplecov#getting-started) does seem like a thing, however, it may only apply...

> when testing a server process (i.e. a JSON API endpoint) via a separate test process (i.e. when using Selenium) where you want to see all code executed by the rails server, and not just code executed in your actual test files, you'll want to add something like this to the top of script/rails (or bin/rails for Rails 4)

**Comment by tpendragon** [comment]
@jpstroop @escowles `SimpleCov.start 'rails'` has always just meant "start up simplecov with config options that make sense for rails projects" to me. So it ignores /spec and categorizes things appropriately.

**Pull request merged**
