### PR TITLE
PDF Cover Page

### LINKED ISSUE #73: PDFs need a boilerplate coverpage
Mudd has this: http://findingaids.princeton.edu/AC044/c0095.pdf

We can probably use the rights statement to trigger different behaviors. We should not go into production w/ the PDF feature until this is sorted out.

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #73

Not the prettiest thing in the world, but it has the necessary data.

### CODE REVIEW

**Comment by tpendragon** [comment]
Example PDF: [fixture_pdf.pdf](https://github.com/pulibrary/plum/files/123481/fixture_pdf.pdf)

**Comment by escowles** [comment]
Can you add the title and source metadata id too?  I think those would round out the necessary cover page info.

**Comment by tpendragon** [comment]
> source metadata id too

Is this useful for a PDF? I'd think better would be embedding metadata, which I think has a ticket

**Comment by escowles** [comment]
I think it's nice to have an ID on the cover page that people could use to uniquely identify the thing they were talking about (e.g., if they want to report a problem, or find it again).  The URI might be better than the source metadata ID.

**Comment by tpendragon** [comment]
> The URI might be better than the source metadata ID.

:+1: to that. @jpstroop?

**Comment by tpendragon** [comment]
There's the title/URI.

**Comment by tpendragon** [comment]
Example: 
[fixture_pdf.pdf](https://github.com/pulibrary/plum/files/123502/fixture_pdf.pdf)

**Comment by escowles** [comment]
:+1: looks good

**Pull request merged**
