### PR TITLE
Add authorized logic.

### PR DESCRIPTION
**Pull request by tpendragon**
Opening this PR largely for discussion about what the business logic around #authorized? should be. A custom role? Anyone who has campus_patron? Anyone who is a curation_concern_creator? Some other role?

### CODE REVIEW

**Comment by tpendragon** [comment]
This logic might be done already via ability.rb

**Comment by tpendragon** [comment]
As it stands, campus patrons can view curation concerns, creators can make them, and admins can manage roles. Should CAS logins just automatically get the patron group?

**Comment by escowles** [comment]
I think having CAS logins automatically get the patron group makes sense.

Definitely another ticket, but having campus IP address ranges also get the group would be nice too.

**Comment by jpstroop** [comment]
I'm working up a quick google doc around what I think our first pass at roles should be. Will plunk a link here in the next 5 minutes.

**Comment by jpstroop** [comment]
https://goo.gl/znB0FR

**Pull request closed without merging**
