### PR TITLE
Pairtree Derivative Paths

### LINKED ISSUE #66: Put derivatives in buckets
* Given the pid `df69azpl`
 * The jp2 should be stored at: `{resolver_root}/df/69/az/pl.jp2` (on the mounted image server storage)
 * So that we can use `http://{server}/loris/df%2F69%2Faz%2Fpl.jp2/...` in views to make image requests

### PR DESCRIPTION
**Pull request by terrellt**
Closes #66

### CODE REVIEW

**Comment by jpstroop** [comment]
Given an image stored at `tmp/08/61/2n/57/q-intermediate_file.jp2`, there should be a way to get the string `08%2F61%2F2n%2F57%2Fq-intermediate_file.jp2`, i.e., the URL-encoded ID that the image server expects. Am I missing it? This seems like the time to add it. 

Loris lets you get away with not having it encoded because [this](http://stackoverflow.com/q/30981696/714478), but we should use the correct syntax in our HTML view and manifests.

**Comment by terrellt** [comment]
@jpstroop Looking at the IIIF Presentation spec I'm not seeing where to put that. Could you modify the following manifest to show the way it should be updated?

```
{  
   "@context":"http://iiif.io/api/presentation/2/context.json",
   "@id":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest",
   "@type":"sc:Manifest",
   "label":"Test",
   "description":"Test",
   "viewingHint":"individuals",
   "viewingDirection":"left-to-right",
   "sequences":[  
      {  
         "@id":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/sequence/normal",
         "@type":"sc:Sequence",
         "canvases":[  
            {  
               "@id":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/canvas/bz60cw30w",
               "@type":"sc:Canvas",
               "label":"color.tif",
               "images":[  
                  {  
                     "@id":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/annotation/bz60cw30w-image",
                     "@type":"oa:Annotation",
                     "motivation":"sc:painting",
                     "resource":{  
                        "@id":"http://192.168.99.100:5004/bz/60/cw/30/w-intermediate_file.jp2/full/!200,200/0/default.jpg",
                        "@type":"dcterms:Image",
                        "format":"image/jpeg",
                        "width":200,
                        "height":287,
                        "service":{  
                           "@context":"http://iiif.io/api/image/2/context.json",
                           "@id":"http://192.168.99.100:5004/bz/60/cw/30/w-intermediate_file.jp2",
                           "profile":"http://iiif.io/api/image/2/level2.json"
                        }
                     },
                     "on":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/canvas/bz60cw30w"
                  }
               ],
               "width":200,
               "height":287
            },
            {  
               "@id":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/canvas/zs25x852h",
               "@type":"sc:Canvas",
               "label":"gray.tif",
               "images":[  
                  {  
                     "@id":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/annotation/zs25x852h-image",
                     "@type":"oa:Annotation",
                     "motivation":"sc:painting",
                     "resource":{  
                        "@id":"http://192.168.99.100:5004/zs/25/x8/52/h-intermediate_file.jp2/full/!200,200/0/default.jpg",
                        "@type":"dcterms:Image",
                        "format":"image/jpeg",
                        "width":200,
                        "height":256,
                        "service":{  
                           "@context":"http://iiif.io/api/image/2/context.json",
                           "@id":"http://192.168.99.100:5004/zs/25/x8/52/h-intermediate_file.jp2",
                           "profile":"http://iiif.io/api/image/2/level2.json"
                        }
                     },
                     "on":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/canvas/zs25x852h"
                  }
               ],
               "width":200,
               "height":256
            }
         ]
      }
   ]
}
```

**Comment by jpstroop** [comment]
Yup, sorry, I could have been clearer.

In the Prezi API under [6.4](http://iiif.io/api/presentation/2.0/#image-resources):
> If a IIIF Image API service is available for the image, then a link to the service’s base URI should be included. The base URI is the URI up to the identifier, but not including the trailing slash character or any of the subsequent parameters.

So, in the service blocks above (this is the first one):

```javascript
"service": {  
    "@context":"http://iiif.io/api/image/2/context.json",
    "@id":"http://192.168.99.100:5004/bz/60/cw/30/w-intermediate_file.jp2", // here
    "profile":"http://iiif.io/api/image/2/level2.json"
}
```
that `@id` should have a value that is the [Base URI](http://iiif.io/api/image/2.0/#uri-syntax) for an IIIF image service. Assuming that the identifier portion of the URI in `@id` above is `bz/60/cw/30/w-intermediate_file.jp2`, that part needs to be escaped to `bz%2F60%2Fcw%2F30%2Fw-intermediate_file.jp2`. So the whole URI would be:

```
http://192.168.99.100:5004/bz%2F60%2Fcw%2F30%2Fw-intermediate_file.jp2",
```

Yar?

See also: 
 * Image API Section 3: http://iiif.io/api/image/2.0/#identifier
 * Image API Section 9: http://iiif.io/api/image/2.0/#uri-encoding-and-decoding

**Comment by terrellt** [comment]
@jpstroop Is this better?

```json
{  
   "@context":"http://iiif.io/api/presentation/2/context.json",
   "@id":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest",
   "@type":"sc:Manifest",
   "label":"Test",
   "description":"Test",
   "viewingHint":"individuals",
   "viewingDirection":"left-to-right",
   "sequences":[  
      {  
         "@id":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/sequence/normal",
         "@type":"sc:Sequence",
         "canvases":[  
            {  
               "@id":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/canvas/bz60cw30w",
               "@type":"sc:Canvas",
               "label":"color.tif",
               "images":[  
                  {  
                     "@id":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/annotation/bz60cw30w-image",
                     "@type":"oa:Annotation",
                     "motivation":"sc:painting",
                     "resource":{  
                        "@id":"http://192.168.99.100:5004/bz%2F60%2Fcw%2F30%2Fw-intermediate_file.jp2/full/!200,200/0/default.jpg",
                        "@type":"dcterms:Image",
                        "format":"image/jpeg",
                        "width":200,
                        "height":287,
                        "service":{  
                           "@context":"http://iiif.io/api/image/2/context.json",
                           "@id":"http://192.168.99.100:5004/bz%2F60%2Fcw%2F30%2Fw-intermediate_file.jp2",
                           "profile":"http://iiif.io/api/image/2/level2.json"
                        }
                     },
                     "on":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/canvas/bz60cw30w"
                  }
               ],
               "width":200,
               "height":287
            },
            {  
               "@id":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/canvas/zs25x852h",
               "@type":"sc:Canvas",
               "label":"gray.tif",
               "images":[  
                  {  
                     "@id":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/annotation/zs25x852h-image",
                     "@type":"oa:Annotation",
                     "motivation":"sc:painting",
                     "resource":{  
                        "@id":"http://192.168.99.100:5004/zs%2F25%2Fx8%2F52%2Fh-intermediate_file.jp2/full/!200,200/0/default.jpg",
                        "@type":"dcterms:Image",
                        "format":"image/jpeg",
                        "width":200,
                        "height":256,
                        "service":{  
                           "@context":"http://iiif.io/api/image/2/context.json",
                           "@id":"http://192.168.99.100:5004/zs%2F25%2Fx8%2F52%2Fh-intermediate_file.jp2",
                           "profile":"http://iiif.io/api/image/2/level2.json"
                        }
                     },
                     "on":"http://127.0.0.1:3000/concern/scanned_books/08612n57q/manifest/canvas/zs25x852h"
                  }
               ],
               "width":200,
               "height":256
            }
         ]
      }
   ]
}
```

**Comment by jpstroop** [comment]
That's correct. Were there changes in the code to make this happen? Not seeing them if so.

**Comment by terrellt** [comment]
@jpstroop Wanted confirmation before I pushed up.

**Comment by terrellt** [comment]
@jpstroop Should be ready for review.

**Comment by jpstroop** [comment]
:+1:

**Pull request merged**
