### PR TITLE
Add navigation date to form.

### LINKED ISSUE #284: Add navDate to create/edit form
See last property here: http://iiif.io/api/presentation/2.1/#technical-properties

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #284

Some questions first: I left the time selectors turned on, but it seems unlikely time would ACTUALLY be entered, yes? Maybe I should turn off the selector and make it always 00:00:00 somehow?

### CODE REVIEW

**Comment by escowles** [comment]
Agree entering time seems pretty unlikely.  How much does it get in the way?  Can the user just ignore the time or do they have to pick something?

**Comment by escowles** [comment]
I could go either way: hiding the time means less clutter and will probably never be a problem (and we can always turn it back on later).  On the other hand, if they don't have to interact, it seems fine to show it and it could hypothetically be known, or used to order multiple items from the same date.

**Comment by escowles** [comment]
The UTC timezone gets trickier if the time is shown (so that's another reason to hide it).  If the time is hidden, then I think we don't need to worry as much about localtime/UTC being off by a day.

**Comment by tpendragon** [comment]
This may just go to cataloguing practices, so it may not be an issue. When someone says it was created on the 19th, is time zone taken into account?

**Comment by tpendragon** [comment]
I think I'm gonna hide the time controls and we can turn them on later.

**Comment by jpstroop** [comment]
> This may just go to cataloguing practices, so it may not be an issue. When someone says it was created on the 19th, is time zone taken into account?

Let's wait for a use case. For now, I think stopping at the day is sufficient.

**Comment by jpstroop** [comment]
The intent is to be able to, e.g., sort serials put them on a calendar, etc. I suppose there could be morning and evening editions of newspapers, but I don't think we have that use case, at least yet. Better to just zero out the time I think.

**Pull request merged**
