### PR TITLE
Looking up manifest by ARK

### LINKED ISSUE #965: Orangelight should be able to find a manifest for an item in Plum based on ARK
Orangelight has the ARK for an item, and needs to lookup the manifest URL

### PR DESCRIPTION
**Pull request by escowles**
Fixes #965

### CODE REVIEW

**Comment by jpstroop** [comment]
FWIW, I like this pattern more that what I had in mind. I was thinking it would be a route something like:

`/resolver?ark=ark:%2F%2F{naan}%2F{noid}`

which would give you a json body something like:

```json
{
  "ark" : "ark://{naan}/{noid}",
  "iiif" : "https://..."
}
```
but unless there are other keys we might want to include, better to just use HTTP as intended.

**Comment by escowles** [comment]
👍  I think this will make it easy for OL to use: no need to encode the ARK, just append it to the base URL of the lookup service, and either get the manifest or a 404 back.

**Comment by jpstroop** [comment]
I agree, and scoping the route to `/iiif` makes it clear. If we ever wanted to resolve PUDL identifiers, we could do `/pudl`, etc.

**Comment by tpendragon** [comment]
Looks good. We'll have to see if UV can follow the redirect, but if it can't we can just parse it ourselves.

**Pull request merged**
