### PR TITLE
Adds ability to generate and download PDF from ScannedBook

### PR DESCRIPTION
**Pull request by flyingzumwalt**
ref #25

Does not add a link/button to show view, but you can trigger this action by visiting /concerns/scanned_books/:id/pdf

Note: There's still work to do, recorded in #64

### CODE REVIEW

**Comment by jpstroop** [comment]
@terrellt can you review when you get a chance? We should probably merge and refine in other issues, but here are a few thoughts:
 1. Should this be made at the same time as other derivatives, or on the first request and then cached with the derivatives? (I believe we're assuming the latter right now).
 2. It should probably respect the IIIF non-paged `viewingHint`, and perhaps ultimately be derived from the Manifest in general. This would allow us to have an [outline](http://prawnpdf.org/api-docs/2.0/Prawn/Outline.html) as well, which would be pretty snazzy.

**Comment by terrellt** [comment]
@jpstroop
1. My inclination is on first request.
2. Agree. #76.

**Comment by terrellt** [comment]
I'm inclined to merge this and push further work down via #76 and #64. Thoughts @jpstroop?

**Comment by jpstroop** [comment]
:+1: As discussed, I'll make a PDF meta ticket that logs some things to consider as we refine this.

**Pull request merged**
