### PR TITLE
Initial METS ingest implementation

### PR DESCRIPTION
**Pull request by escowles**

### CODE REVIEW

**Comment by escowles** [comment]
Here is a sample object ingested with this rake task: https://hydra-dev.princeton.edu/concern/scanned_resources/3t945q79m

**Comment by tpendragon** [comment]
@escowles Is labeling the files that are ingested going to happen in another PR?

**Comment by jpstroop** [comment]
The images don't match the object: http://pudl.princeton.edu/sheetreader.php?obj=d217qp581 cache problem again?

**Comment by escowles** [comment]
I've updated to use the FileSetActor, which handles the initial file labels and derivatives correctly.  Updated example: https://hydra-dev.princeton.edu/concern/scanned_resources/05741r719

**Pull request merged**
