### PR TITLE
IIIF Property Validation

### LINKED ISSUE #58: Add validations for values of IIIF predicates

### PR DESCRIPTION
**Pull request by terrellt**
Closes #58

### CODE REVIEW

**Comment by jpstroop** [comment]
Squash?

**Comment by terrellt** [comment]
@jpstroop I left the two kinds of validations in their own commits, but squashed the rubocop commit.

**Comment by jpstroop** [comment]
Why are the [`valid_viewing_hints`](https://github.com/pulibrary/plum/pull/60/files#diff-9abc6a93a8134579b4e1fcb9bf652425R14) Arrays?

**Comment by terrellt** [comment]
@jpstroop RDF's an open world, so property declarations in ActiveTriples result in arrays as the returned values. It's a good way to validate that there aren't multiple hints, too.

**Comment by jpstroop** [comment]
Sure, OK. Just have to make sure we get them converted to Strings when we serialize the Manifests.

**Pull request merged**
