### PR TITLE
Add IIIF schema.

### PR DESCRIPTION
**Pull request by terrellt**
Work towards #50 

What this doesn't include is validation and any form work.

### CODE REVIEW

**Comment by jpstroop** [comment]
Should we consider adding it to the RDF::Vocab gem once IIIF/iiif.io#551 is fixed?

**Comment by terrellt** [comment]
@jpstroop https://github.com/ruby-rdf/rdf-vocab/blob/develop/lib/rdf/vocab/iiif.rb The ontology is there already, this is more like the accessors for mapping from instance methods to predicates.

**Comment by terrellt** [comment]
I added a spec in there to make sure the viewing hint on GenericFile would update, and it appears to - maybe I should just delete that spec?

**Comment by jpstroop** [comment]
I guess you're technically testing the behavior of GenericFile here and therefore shouldn't have to, but I'm not going to complain about an extra spec.

**Comment by terrellt** [comment]
@jpstroop I'm gonna remove it and trust our layers. Extra second of spec for something I can't make fail doesn't seem worth it.

**Comment by jpstroop** [comment]
Heh, fair enough. But did we decide that we're storing the literals instead?

https://github.com/pulibrary/plum/blob/iiif_properties/spec/models/generic_file_spec.rb#L8

**Comment by jpstroop** [comment]
(Maybe I don't understand what that code is doing well enough....)

**Comment by terrellt** [comment]
@jpstroop That's just making sure that the method #viewing_hint maps to the viewingHint predicate. The literals stuff will come in for the validation PR.

**Pull request merged**
