### PR TITLE
Implement Bulk Label Interface

### LINKED ISSUE #7: Easy interface to bulk add labels to a set of pages

### LINKED ISSUE #170: Jasmine for Javascript?
It's been a while since I've looked at the state of integrating Jasmine with Rails, but maybe it's in a good place now?

### PR DESCRIPTION
**Pull request by tpendragon**
This is an interface for bulk labeling/previewing/persisting those
labels. Closes #7, closes #170

### CODE REVIEW

**Comment by tpendragon** [comment]
screen shot 2015-11-24 at 12 49 40 pm

This is what it looks like.

**Comment by escowles** [comment]
This looks very nice.  I spun it up locally and played with it and everything worked as expected, except:
* the updates didn't trigger reindexing in Solr
* clicking Save didn't take me back to the ScannedResource (or we add a button to go back to the ScannedResource)

**Comment by tpendragon** [comment]
> the updates didn't trigger reindexing in Solr

Are you sure? It's using the file set update action, this would be odd. Steps to reproduce?

**Comment by escowles** [comment]
You're right -- it is updated Solr.  It's just that the ScannedResource view of the FileSets is using ebucore:filename instead of dc:title, so the display wasn't updated.  I've created #183 for using dc:title (if available).

**Comment by tpendragon** [comment]
@escowles Added a link back to parent.

**Pull request merged**
