### PR TITLE
Run at new PDF Rendering.

### PR DESCRIPTION
**Pull request by tpendragon**
Attempt at a new PDF Format

### CODE REVIEW

**Comment by tpendragon** [comment]
Looks like the following right now:

[fixture_pdf.pdf](https://github.com/pulibrary/plum/files/148665/fixture_pdf.pdf)

**Comment by escowles** [comment]
This is looking very nice!  The only suggestion I have is underlining the URL.

**Comment by jpstroop** [comment]
I think the logo and labels could be smaller, but agree, it seems like we're on the right path.

**Comment by jpstroop** [comment]
This sample from the Beinecke is interesting, though there's less info than their group wants.

I sort of like the padding around the image as well, but that's probably a separate conversation.

[Beinecke_DL_2016480_1010185.pdf](https://github.com/pulibrary/plum/files/148674/Beinecke_DL_2016480_1010185.pdf)

**Comment by tpendragon** [comment]
Add address to holding location, and add metadata.

**Pull request merged**
