### PR TITLE
Better collapse functionality for Structure

### PR DESCRIPTION
**Pull request by tpendragon**
Now dragging into a collapsed structure won't expand it, and dragging
right of a collapsed structure creates a new node.

### CODE REVIEW

**Comment by tpendragon** [comment]
https://vimeo.com/167344323 Demo of the new process. @jpstroop @joycebcat ?

**Comment by jpstroop** [comment]
That looks better to me. So a structure has to be collapsed in order to create a sibling? I think that makes sense.

**Comment by tpendragon** [comment]
@jpstroop It doesn't -have- to, you can make one the same way you used to - drag too far and then drag left. You just -can- do it this way now.

**Comment by joycebcat** [comment]
@tpendragon I am unable to replicate what I see in the video.  Is it in hydra-dev now?  Everytime I try to create a new section as shown, the collapsed section pops open and either nothing new is created or they end up nested under the first section.  I find that I have sometimes actually changed the order of the images while I'm trying to create a section where I want to place it.

**Comment by tpendragon** [comment]
No, it won't be on hydra dev until this PR is merged. Sorry for the confusion!

**Pull request merged**
