### PR TITLE
Re-organize welcome page to accommodate geo works

### LINKED ISSUE #845: Re-organize landing page
Re-organize landing page to accommodate Geo works. Divide into sections based on type? A 'Book' section and a 'Geo' section.

How it looks now:

screenshot 2016-11-30 10 11 00

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #845. Re-organizes the welcome page to accommodate geo works. Thoughts? Comments?

screenshot 2016-12-02 16 43 36

### CODE REVIEW

**Comment by jpstroop** [comment]
I like it. :+1:

**Comment by escowles** [comment]
👍  — though I feel like we need some icons for the different types (or to reduce the whitespace)

**Comment by jpstroop** [comment]
Icons would be cool.

**Comment by jpstroop** [comment]
Also: are Collections really unique to book-like stuff?

**Comment by eliotjordan** [comment]
@jpstroop No. At this point collections aren't unique. They can be in their own section, however, a section of one looks a little strange. I can do that and see show you how it looks.

**Comment by eliotjordan** [comment]
After too much time wrestling with SVGs and the asset pipeline, here's the the latest welcome page iteration:

screenshot 2016-12-05 18 19 27

**Comment by tpendragon** [comment]
@eliotjordan That looks awesome!

**Comment by jpstroop** [comment]
Wow!

-Js

Sent via mobile. Please excuse typos, brevity, etc.

On Dec 5, 2016 9:08 PM, "Trey Pendragon" <notifications@github.com> wrote:

@eliotjordan <https://github.com/eliotjordan> That looks awesome!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/pulibrary/plum/pull/856#issuecomment-265039817>, or mute
the thread

**Pull request merged**
