### PR TITLE
Implementing IIIF token auth

### LINKED ISSUE #466: Implement IIIF Token Auth

### PR DESCRIPTION
**Pull request by escowles**
Closes #466

### CODE REVIEW

**Comment by tpendragon** [comment]
I might be missing something here. Does this actually auth a user via CAS and give them a token to maintain that auth? It looks more like it'll give a token to whoever asks and treat them as if they're on campus?

**Comment by escowles** [comment]
Oh, right -- I do need to make sure they're authenticated before I give them the token...

**Comment by tpendragon** [comment]
:+1: I think the token needs to be associated with the user they're authenticated as too.

**Comment by escowles** [comment]
The token now includes the user's email in addition to the expiration timestamp.  So the controller uses the email to lookup their user object.

**Comment by tpendragon** [comment]
Trying this out on UV, might take me a bit.

**Comment by escowles** [comment]
Sounds good -- definitely want to make sure it really works.

**Pull request closed without merging**
