### PR TITLE
Sorting UI for Scanned Resources

### PR DESCRIPTION
**Pull request by tpendragon**
This allows scanned resources' FileSets to be re-ordered via JQuery-UI
Sortable.

### CODE REVIEW

**Comment by tpendragon** [comment]
Rebased.

**Comment by tpendragon** [comment]
UI looks like:

screen shot 2015-11-03 at 11 27 14 am

**Comment by jpstroop** [comment]
Do you want to add the ability to update properties about the page/book, similar to what's in that demo I mocked up (https://github.com/pulibrary/pages-editor-mockup), or merge and make separate issues?

**Comment by jpstroop** [comment]
I guess that's #62, but it's probably something we should have for the week of the 30th.

**Pull request merged**
