### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by tpendragon**
The CSS is a little wonky here, but I can't seem to figure out why the color's missing and some of the styles aren't being applied. @axamei ?

### CODE REVIEW

**Comment by axamei** [comment]
@tpendragon Is it only the background color of the secondary header and bottom portion of footer?

**Comment by tpendragon** [comment]
@axamei The fonts and color of the text has changed too.

**Comment by axamei** [comment]
@tpendragon It looks like the order of the partials is the issue. Try moving https://github.com/pulibrary/plum/blob/update_everything/app/assets/stylesheets/application.css.scss#L49 up higher in the application.scss file. Try line 24.

**Comment by tpendragon** [comment]
@axamei That didn't change anything.

**Comment by axamei** [comment]
Strange. I get the following on my local when I moved browse_everything up.

screen shot 2016-05-13 at 11 48 51 am

**Comment by tpendragon** [comment]
@axamei Yeah, log in. Right now the text in top left is wrong, but the boxes will be -very- wrong if you log in as an admin.

**Comment by tpendragon** [comment]
@axamei You'll also notice the magnifying glass is just a little off.

**Comment by axamei** [comment]
Top left text should be serif? I see the magnifying glass is off. How should the boxes look?

**Pull request merged**
