### PR TITLE
Displaying FileSet technical metadata

### LINKED ISSUE #828: Show technical and preservation metadata on FileSet #show page
Will help w/ mismatched checksums.

### PR DESCRIPTION
**Pull request by escowles**
Closes #828

### CODE REVIEW

**Comment by escowles** [comment]
I looked at a TIFF in Fedora, and there are several other properties that could be added here:

* hydrafits:valid "true"
* hydrafits:wellFormed "true"
* exif:colorSpace "RGB"
* exif:exifVersion "9.13"
* exif:orientation "normal*"
* sweetjpl:byteOrder "big endian"
* mix:colorProfileName "Adobe RGB (1998)"
* mix:colorProfileVersion "2.1.0"
* mix:compressionScheme "Uncompressed"
* premis:hasCreatingApplicationVersion "0.8.6" (FITS version)

We talked about adding the valid/wellformed properties — do we want any of the others?

**Comment by jpstroop** [comment]
@escowles I made checkboxes.

**Comment by jpstroop** [comment]
No pronom ID though, right?

**Comment by escowles** [comment]
No, it looks like pronom id isn't mapped.

**Comment by jpstroop** [comment]
OK. Right now MIME/media type probably doesn't make sense, but it might eventually.

**Comment by escowles** [comment]
Here's what the new properties look like:

screen shot 2016-11-18 at 4 42 12 pm

**Comment by eliotjordan** [comment]
This looks good to me. I just tested this with geo objects, and it works just fine. Any reason to wait on merging this @escowles?

**Comment by escowles** [comment]
@eliotjordan No, I think this is ready to go.

**Pull request merged**
