### PR TITLE
Return parents when searching for child metadata.

### LINKED ISSUE #93: Labels for a bookset's scanned books can be searched and will return the bookset

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #93

### CODE REVIEW

**Comment by tpendragon** [comment]
This solr query might not be very performant, but I couldn't get anything else to work

**Comment by escowles** [comment]
I guess the question is whether we'd rather have bad search-time performance (doing the join) or bad index-time performance (loading the children and indexing their values in the parent record).

**Comment by tpendragon** [comment]
I wish I could get it to work with a filter query

**Comment by tpendragon** [comment]
@escowles Yeah. I suspect since this is an ingest tool that we're less worried about query performance we can't even measure yet. @jpstroop?

**Comment by tpendragon** [comment]
This breaks the show view for scanned resources with parents. I'll work on that after lunch.

**Comment by tpendragon** [comment]
Fixed, ready for review

**Pull request merged**
