### PR TITLE
Only allow crawling for Production.

### LINKED ISSUE #571: Add robots.txt
@kevinreiss pointed out that hydra-dev is showing up in [Google results](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=princeton+blacklight). Fine since you can do anything w/o logging in, but we should probably try to keep it out to whatever extent we can.

Do we want to reconsider putting it behind the firewall? It's a massive pain for demos, but throwing it out there....

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #571

### CODE REVIEW

**Comment by tpendragon** [comment]
After we get this worked out, need to do the same for Pom.

**Comment by jpstroop** [comment]
Integration spec, or simple enough?

**Comment by tpendragon** [comment]
I can do view and controller specs, probably, concerned about what stubbing out Rails.env will do. Give me a few.

**Comment by tpendragon** [comment]
@jpstroop ?

**Comment by escowles** [comment]
👍

**Pull request merged**
